fix: forceNewDeployment to be a boolean
aws-actions/amazon-ecs-deploy-task-definition pull request #140
Opened 2020-11-10 17:54 UTC by paragbhingre

*This PR fix the Issue [#133](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/133)*

*Description of changes:*
This issue was occurring due to incorrect data type of the forceNewDeployment parameter.
In order to fix this issue, I have type caste the value of the forceNewDeployment parameter from string to boolean.

2020-11-11 21:45 UTC, allisaurus commented on index.js
> +    const forceNewDeployInput = core.getInput('force-new-deployment', { required: false })
this line appears to be missing a terminal `;`

2020-11-11 21:51 UTC, piradeepk commented on index.test.js
> +            forceNewDeployment: false
the name of this test is force new deployment, but you're giving it a value of false (shouldn't this be false by default/wouldn't you want to test true?)

2020-11-11 21:53 UTC, piradeepk commented on index.js
> +    const forceNewDeployment = forceNewDeployInput != undefined && forceNewDeployInput.toLocaleLowerCase === "true" ? true : false;
nit since your conditional returns true or false, do you need to explicitly define `? true : false`?

2020-11-11 21:53 UTC, allisaurus commented on index.js
> +    const forceNewDeployment = forceNewDeployInput != undefined && forceNewDeployInput.toLocaleLowerCase === "true" ? true : false;
let's use `.toLowerCase` instead, since we're not passing in a locale value

2020-11-11 22:10 UTC, allisaurus requested changes

2020-11-11 22:10 UTC, allisaurus commented on index.test.js
> +            forceNewDeployment: false
this condition is not correct - this test is meant to test the _success_ of passing in `forceNewDeployment`, so we would expect `ecs:update-service` to be called with this param set as `true`. If this is not occurring, either the setup of the test is wrong or the change is not behaving as we expect.

2020-11-11 22:10 UTC, allisaurus commented on index.js
> +    const forceNewDeployment = forceNewDeployInput != undefined && forceNewDeployInput.toLocaleLowerCase === "true" ? true : false;
also, nit: I'd prefer we wrap the 2 conditions of the ternary operator in parenthesis to make it clear they're being evaluated together to determine the return condition

2020-11-12 00:44 UTC, piradeepk commented on index.js
> +    const forceNewDeployment = forceNewDeployInput != undefined && (forceNewDeployInput.toLowerCase === 'true' || forceNewDeployInput);
Curious why you're adding the || forceNewDeployInput as a condition here?

2020-11-12 14:36 UTC, piradeepk approved these changes
Ship it! 💯 Thanks for fixing this so quickly @paragbhingre!

2020-11-12 14:38 UTC, merged

2020-11-18 18:53 UTC, ltamrazov commented
hi, thank you for this fix! 

@piradeepk When can we expect a release with this revision?

Thank you!