Add new integration tests for newly added one off task
aws-actions/amazon-ecs-deploy-task-definition pull request #594
Opened 2024-07-30 20:20 UTC by shesaave

*Issue #, if available:* https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/54 and https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/304 and https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/273

*Description of changes:* Added changes to test one-off task inputs 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-30 21:14 UTC, amazreech requested changes
Blocking Automatic Merging, waiting for additional approvals.

2024-07-31 12:52 UTC, omkhegde commented on task-definition-run-task.json
> +
unnecessary newline

2024-07-31 14:03 UTC, amazreech commented on .github/workflows/test-workflow.yml
>      - name: Deploy Amazon ECS task definition
nit: we can remove this to "Deploy Amazon ECS task definition to an ECS Service" for clarity.

2024-07-31 14:40 UTC, amazreech approved these changes

2024-07-31 14:45 UTC, omkhegde approved these changes

2024-07-31 14:55 UTC, merged